name: Node Workflow

on:
  workflow_call:
    inputs:
      node-version:
        description: 'The Node.js version to use'
        required: false
        default: '22'
        type: string
      upload-artifact:
        description: Whether to push the build output as a GHA Artifact.
        required: false
        default: false
        type: boolean
      github-runner:
        description: 'The Linux runner to use'
        required: false
        default: 'ubuntu-latest'
        type: string
      artifact-name:
        description: "Name of the artifact to build and upload"
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      project-path:
        description: 'Path to the Node.js project within the repository'
        required: false
        default: '.'
        type: string


jobs:
  node:
    runs-on: ${{ inputs.github-runner }}
    defaults:
      run:
        working-directory: ${{ inputs.project-path }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${{ inputs.node-version }}'
          cache: 'npm'
          cache-dependency-path: '${{ inputs.project-path }}/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload dist
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.project-path }}/dist/
