name: Go Workflow

on:
  workflow_call:
    inputs:
      go-version:
        description: 'The Go version to use'
        required: false
        default: '1.22'
        type: string
      github-runner:
        description: 'The GitHub runner to use'
        required: false
        default: 'ubuntu-latest'
        type: string

jobs:
  build:
    runs-on: ${{ inputs.github-runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}

      - name: Lint
        run: |
          changes=$(go fmt .)
          if [[ ! -z $changes ]]; then
            echo "Linter detected changes in these files"
            echo "$changes"
            exit 1
          fi

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
