name: Reusable Docker build and publish workflow

on:
  workflow_call:
    inputs:
      extra-build-cmd:
        description: Command to run before the image gets built.
        required: false
        type: string
      publish-image:
        description: Whether to publish the image to GHCR.
        required: false
        default: false
        type: boolean
      upload-artifact:
        description: Whether to push the image as a GHA Artifacts.
        required: false
        default: false
        type: boolean
      artifact-name:
        description: "Name of the artifact to build and upload"
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      github-runner:
        description: The GitHub runner to use.
        required: false
        default: ubuntu-latest
        type: string
      docker-registry-url:
        description: Container registry URL. Defaults to ghcr.io.
        required: false
        default: ghcr.io
        type: string
      docker-registry-username:
        description: Username to authenticate to the container registry.
        default: ${{ github.actor }}
        type: string
    secrets:
      docker-registry-token:
        description: Token used to authenticate to the container registry.
        required: false
      EXTRA_COMMAND_SECRET:
        description: Secret to pass to the extra command, if any.
        required: false
    outputs:
        artifact-name:
          description: "Name of the artifact that was uploaded"
          value: ${{ jobs.docker.outputs.artifact-name }}

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ${{ inputs.github-runner }}
    outputs:
      version: ${{ steps.meta.outputs.version }}
      artifact-name: ${{ steps.upload-artifact.outputs.artifact-name }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.REGISTRY_URL }}/${{ env.IMAGE_NAME }}

      - name: Execute EXTRA_COMMAND (if provided)
        if: ${{ inputs.EXTRA_COMMAND != '' }}
        env:
          EXTRA_COMMAND_SECRET: ${{ secrets.EXTRA_COMMAND_SECRET }}
        run: ${{ inputs.EXTRA_COMMAND }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        if: %{{ inputs.publish-image }}
        with:
          registry: ${{ inputs.github-registry-url }}
          username: ${{ inputs.github-registry-username }}
          password: ${{ secrets.docker-registry-token }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ inputs.publish-image }}
          load: true
          tags: localbuild:${{ github.sha }}

      - name: Build Docker image as tarball
        if: ${{ inputs.upload-artifact }}
        run: |
          docker save localbuild:${{ github.sha }} -o docker-image-${{ inputs.artifact-name }}.tar

      - name: Upload Docker image tarball
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ inputs.artifact-name }}.tar
          path: docker-image-${{ inputs.artifact-name }}.tar
          retention-days: 1
