name: Go Workflow

on:
  workflow_call:
    inputs:
      go-version:
        description: 'The Go version to use'
        required: false
        default: '1.22'
        type: string
      upload-artifact:
        description: Whether to push the image as a GHA Artifacts.
        required: false
        default: false
        type: boolean
      linux-runner:
        description: 'The Linux runner to use'
        required: false
        default: 'ubuntu-latest'
        type: string
      windows-runner:
        description: 'The Windows runner to use'
        required: false
        default: 'windows-latest'
        type: string
      macos-runner:
        description: 'The macOS runner to use'
        required: false
        default: 'macos-latest'
        type: string

jobs:
  golang:
    strategy:
      matrix:
        os:
          - "${{ inputs.linux-runner }}"
          - "${{ inputs.windows-runner }}"
          - "${{ inputs.macos-runner }}"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}

      - name: Lint
        run: |
          changes=$(go fmt ./...)
          if [[ ! -z "$changes" ]]; then
            echo "Linter detected changes in these files:"
            echo "$changes"
            exit 1
          fi
        shell: bash

      - name: Build
        run: go build -v -o build/${{ runner.os }}/app ./...

      - name: Test
        run: go test -v ./...

      - name: Upload binary
        if: success() && ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: go-binary-${{ runner.os }}
          path: build/${{ runner.os }}/app
